language: node_js
os:
  - linux
  - osx
node_js:
  - node
  - lts/*
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter; fi
  - chmod +x ./cc-test-reporter
  - npm i -g codacy-coverage
before_script:
  - ./cc-test-reporter before-build
after_script:
  - $(npm bin)/nyc report -r lcov
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - cat coverage/lcov.info | codacy-coverage
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: true
